name: Update on Release

on:
  push:
    tags:
      - '*'

jobs:
  updateOnRelease:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run a script
      run: |
        echo "Add commands or scripts here"
        # Additional commands
